### ISSUE TITLE
Provide Recursive Hierarchy Features

### ISSUE THREAD

**Issue by denizul** [ditrit/OGREE-APIv3#14]
For all entities recursive hierarchy. For example
The command below gets the building, all rooms, all racks, all devices

`
{base}/buildingID/all 
`

**Comment by denizul** [comment]
Added the following ranged endpoints:

//TENANT
API Call GET {BASE}/tenants/{tenant_name}/all/sites/buildings
API Call GET {BASE}/tenants/{tenant_name}/all/sites/buildings/rooms
API Call GET {BASE}/tenants/{tenant_name}/all/sites/buildings/rooms/racks

//SITE
API Call GET {BASE}/sites/{site_id}/buildings/rooms
API Call GET {BASE}/sites/{site_id}/buildings/rooms/racks

//BUILDING
API Call GET {BASE}/buildings/{building_id}/rooms/racks

**Comment by hchybz** [comment]
Ziad, Missing needed one !


API call GET {base}/device/{device_id}/all

**Comment by Cedrok** [comment]
Missing calls with current method:
- From room to 1st devices (LOD2): should be GET {BASE}/rooms/{room_id}/racks/devices
- From rack to devices of 2nd level (LOD2): should be GET {BASE}/racks/{rack_id}/devices/devices ?
- All calls for devices
  - GET {BASE}/devices/{device_id}/devices <= LOD1
  - GET {BASE}/devices/{device_id}/devices/devices <= LOD2

New method:
To be more readable, switch calls to `GET {BASE}/category/{obj_id}/levels={0|1|2}` syntax ? (cf com from 30/04)
eg: 
- get all racks from a given room: GET {BASE}/rooms/{room_id}/levels=1
- get 1 level of devices from a rack (chassis only): GET {BASE}/racks/{rack_id}/levels=1
- get 2 levels of devices from a rack (chassis + blades): GET {BASE}/racks/{rack_id}/levels=2
- get first level of a device: GET {BASE}/devices/{device_id}/levels=1

**Comment by hchybz** [comment]
... brainstorming all 3 together .. 

string[] categories = { "tenants", "sites", "buildings", "rooms", "racks", "chassis", "slot", "sfp" };
string[] categories = { "tenants", "sites", "buildings", "rooms", "racks", "chassis", "blade", "adapter", "sfp" };
string[] categories = { "tenants", "sites", "buildings", "rooms", "racks", "chassis", "blade", "adapter" };
string[] categories = { "tenants", "sites", "buildings", "rooms", "racks", "chassis", "blade", "processor" };
string[] categories = { "tenants", "sites", "buildings", "rooms", "racks", "chassis", "blade", "dimm" };
string[] categories = { "tenants", "sites", "buildings", "rooms", "racks", "server", };           
string[] categories = { "tenants", "sites", "buildings", "rooms", "racks", "server", "processor"};
string[] categories = { "tenants", "sites", "buildings", "rooms", "racks", "switch", };           

string[] categories = { "tenants", "sites", "buildings", "rooms", "racks", "device1", "devices2", "devices3"};
string[] categories = { "tenants", "sites", "buildings", "rooms", "racks", "devices", "subdevices1", "subdevices2"};
                           0         1         2            3        4         5          6                7

        GET {BASE}/devices/{device_id}/subdevices1             <= LOD1
        GET {BASE}/devices/{device_id}/subdevices1/subdevices2 <= LOD2
or 
        GET {BASE}/devices/{device_id}/subdevices/components     <<  chassis / blade / components
        GET {BASE}/devices/{device_id}/components                <<  server / components


==> decided   : GET {BASE}/devices/{device_id}/subdevices1/subdevices2

**Comment by denizul** [comment]
J'ajoute les endpoints:
//DEVICE
API call GET {base}/devices/{device_id}/all
API call GET {base}/device_id/subdevices/{subdevice_name}

//RACK
API call GET {base}/racks/{rack_id}/devices/{device_name}/subdevices
API call GET {base}/racks/{rack_id}/devices/{device_name}/subdevices/{subdevice_name}



//ROOM
API call GET {base}/rooms/{room_id}/racks/{rack_name}/devices/{device_name}/subdevices
API call GET {base}/rooms/{room_id}/racks/{rack_name}/devices/{device_name}/subdevices/{subdevice_name}


//BLDG
API call GET {base}/buildings/{building_id}/rooms/{room_name}/racks/{rack_name}/devices/{device_name}/subdevices
API call GET {base}/buildings/{building_id}/rooms/{room_name}/racks/{rack_name}/devices/{device_name}/subdevices/{subdevice_name}


//SITE
API call GET {base}/sites/{site_id}/buildings/{building_name}/rooms/{room_name}/racks/{rack_name}/devices/{device_name}/subdevices
API call GET {base}/sites/{site_id}/buildings/{building_name}/rooms/{room_name}/racks/{rack_name}/devices/{device_name}/subdevices/{subdevice_name}


//TENANT
API call GET {base}/tenants/{tenant_name}/sites/{site_name}/buildings/{building_name}/rooms/{room_name}/racks/{rack_name}/devices/{device_name}/subdevices
API call GET {base}/tenants/{tenant_name}/sites/{site_name}/buildings/{building_name}/rooms/{room_name}/racks/{rack_name}/devices/{device_name}/subdevices/{subdevice_name}



Added the following ranged endpoints:

//TENANT
API call GET {BASE}/tenants/{tenant_name}/all/sites/buildings/rooms/racks/devices

//SITE
API Call GET {BASE}/sites/{site_id}/buildings/rooms/racks/devices

//BUILDING
API Call GET {BASE}/buildings/{building_id}/rooms/racks/devices

**Comment by denizul** [comment]
J'ajoute les endpoints:

//DEVICE
API call GET {base}/devices/{device_id}/all
API call GET {base}/device_id/subdevices/
API call GET {base}/device_id/subdevices/{subdevice_name}
API call GET {base}/device_id/subdevices/{subdevice_name}/subdevice1s
API call GET {base}/device_id/subdevices/{subdevice_name}/subdevice1s/{subdev1_name}

//RACK
API call GET {base}/racks/{rack_id}/devices/{device_name}/subdevices/subdevice1s
API call GET {base}/racks/{rack_id}/devices/{device_name}/subdevices/{subdevice_name}/subdevice1s/{subdev1_name}
API call GET {base}/racks/{rack_id}/all/devices/subdevices



//ROOM
API call GET {base}/rooms/{room_id}/racks/{rack_name}/devices/{device_name}/subdevices/subdevice1s/{subdevice1_name}

API call GET {base}/rooms/{room_id}/racks/{rack_name}/devices/{device_name}/subdevices/{subdevice_name}/subdevice1s

API Call GET {base}/rooms/{room_id}/all/racks/devices/subdevices


//BLDG
API call GET {base}/buildings/{building_id}/rooms/{room_name}/racks/{rack_name}/devices/{device_name}/subdevices/{subdevice_name}/subdevice1s

API call GET {base}/buildings/{building_id}/rooms/{room_name}/racks/{rack_name}/devices/{device_name}/subdevices/{subdevice_name}/subdevice1s/{subdev1_name}

API call GET {base}/buildings/{building_id}/all/rooms/racks/devices

API call GET {base}/buildings/{building_id}/all/rooms/racks/devices/subdevices


//SITE
API call GET {base}/sites/{site_id}/buildings/{building_name}/rooms/{room_name}/racks/{rack_name}/devices/{device_name}/subdevices/subdevice1s/{subdevice1_name}

API call GET {base}/sites/{site_id}/buildings/{building_name}/rooms/{room_name}/racks/{rack_name}/devices/{device_name}/subdevices/{subdevice_name}/subdevice1s

API call GET {base}/site/{site_id}/all/buildings/rooms/racks/devices/subdevices

//TENANT
API call GET {base}/tenants/{tenant_name}/sites/{site_name}/buildings/{building_name}/rooms/{room_name}/racks/{rack_name}/devices/{device_name}/subdevices/{subdevice_name}/subdevice1s

API call GET {base}/tenants/{tenant_name}/sites/{site_name}/buildings/{building_name}/rooms/{room_name}/racks/{rack_name}/devices/{device_name}/subdevices/{subdevice_name}/subdevice1s/{sd1_name}

API call GET {BASE}/tenants/{tenant_name}/all/sites/buildings/rooms/racks/devices/subdevices

**Comment by Cedrok** [comment]
No more modification with Cockroach DB
