### ISSUE TITLE
Adapt GET requests to API REST compliant

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGREE-APIv3#16]
All GET requests should have the same structure (basic ones with ID and queries) 
https://nextcloud.ditrit.io/index.php/f/134763

**Comment by denizul** [comment]
I checked that the multi entity responses should return an 'objects' collection in the JSON response

**Comment by denizul** [comment]
The objects array (collection) will only be returned from endpoints that return multi entity. Single entity endpoints will not return objects collection
